---
title: "p8105_hw2_xz3173"
author: "Xue Zhang"
date: "2023-09-27"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

# Problem 1


Import the pols-month.csv, unemployment.csv, and snp.csv.


```{r}
pols_month_df = 
  read_csv("data/pols-month.csv") |>
  janitor::clean_names() |>
  separate(mon, into = c("year", "month", "day"), sep = "-", convert = TRUE) |>
  
  mutate(
    month = case_match(
      month,
      1 ~ "Jan",
      2 ~ "Feb", 
      3 ~ "Mar", 
      4 ~ "Apr", 
      5 ~ "May", 
      6 ~ "Jun", 
      7 ~ "Jul",
      8 ~ "Aug", 
      9 ~ "Sep", 
      10 ~ "Oct", 
      11 ~ "Nov", 
      12 ~ "Dec")
  ) |>
  
  mutate(
    president = ifelse(grepl("1", prez_dem, ignore.case = TRUE), "dem",
                       ifelse(grepl("1", prez_gop, ignore.case = TRUE), "gop", NA))) |>
  select(-prez_dem, -prez_gop, -day, -gov_gop, -sen_gop, -rep_gop, -gov_dem, -sen_dem, -rep_dem)
```
 
 
Clean snp.csv dataset.
 
```{r}
snp_df = 
  read_csv("data/snp.csv") |>
  janitor::clean_names() |>
  mutate(date = as.Date(date, format = "%m/%d/%y")) |>
  separate(date, into = c("year", "month", "day"), sep = "-", convert = TRUE) |>
  mutate(
    month = case_match(
      month,
      1 ~ "Jan",
      2 ~ "Feb", 
      3 ~ "Mar", 
      4 ~ "Apr", 
      5 ~ "May", 
      6 ~ "Jun", 
      7 ~ "Jul",
      8 ~ "Aug", 
      9 ~ "Sep", 
      10 ~ "Oct", 
      11 ~ "Nov", 
      12 ~ "Dec")) |>
  select(-day)
```
 

Tidy the unemployment data





```{r}
unemployment_df = 
  read_csv("data/unemployment.csv") |>
  janitor::clean_names() |>
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "percent_of_unemployment"
  ) |>
  mutate(
    month = str_to_title(month)
  )
```

Merge the datasets.

```{r}
merged_data =
  merge(pols_month_df, snp_df, by = c("year", "month"), all.x = TRUE)

final_merged_data = 
  merge(merged_data, unemployment_df, by = c("year", "month"), all = TRUE)
```





